### ISSUE TITLE
Tic Tac Toe game using C

### ISSUE THREAD

**Issue by pheonix-official** [pheonix-official/C-Program#8]
Develop a game Tic-Tac-toe using c language

**Comment by shubhamburad** [comment]
#selfassign

**Comment by meprajwal** [comment]
Do assigin it to me.

**Comment by rachannzz** [comment]
assign me

**Comment by pheonix-official** [comment]
fixed by @meprajwal  in [tic_tac_toe.c](https://github.com/pheonix-official/C-Program/commit/6e5cce32ad8303c5cb898b1a463d96fa36a9cd16)
